services:
  producer:
    image: kafka-reader
    command: /app/kafka-writer -topic=topic -message="test message" -bootstrap-servers=kafka-0:9092,kafka-1:9092,kafka-2:9092 -schema-registry=http://schema-registry:8081
    networks:
      - kafka-learn_kafka-network

  single-consumer-1:
    image: kafka-reader
    restart: unless-stopped
    command: /app/kafka-reader -group-id=0 -topic=topic  -mode=single -bootstrap-servers=kafka-0:9092,kafka-1:9092,kafka-2:9092 -schema-registry=http://schema-registry:8081
    networks:
      - kafka-learn_kafka-network

  single-consumer-2:
    image: kafka-reader
    restart: unless-stopped
    command: /app/kafka-reader -group-id=0 -topic=topic  -mode=single -bootstrap-servers=kafka-0:9092,kafka-1:9092,kafka-2:9092 -schema-registry=http://schema-registry:8081
    networks:
      - kafka-learn_kafka-network

  batch-consumer-1:
    image: kafka-reader
    restart: unless-stopped
    command: /app/kafka-reader -group-id=1 -topic=topic  -mode=batch -bootstrap-servers=kafka-0:9092,kafka-1:9092,kafka-2:9092 -schema-registry=http://schema-registry:8081
    networks:
      - kafka-learn_kafka-network

  batch-consumer-2:
    image: kafka-reader
    restart: unless-stopped
    command: /app/kafka-reader -group-id=1 -topic=topic  -mode=batch -bootstrap-servers=kafka-0:9092,kafka-1:9092,kafka-2:9092 -schema-registry=http://schema-registry:8081
    networks:
      - kafka-learn_kafka-network

networks:
  kafka-learn_kafka-network:
    external: true